### ISSUE TITLE
Continuation of #906

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP#1594] opened 2017-01-27 19:10 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

I am using the latest version of the PowerShell scripts by using Install-Module SharePointPnPPowerShellOnline -AllowClobber

I enclose the output from Set-SPOTraceLog -On -LogFile c:\temp\logfile2.txt -Level Debug

The error message was 👎 

PS C:\Windows\system32> Apply-SPOProvisioningTemplate -Path "c:\temp\lookup-template.xml"
Apply-SPOProvisioningTemplate : Invalid field name. {3a18fcce-7eab-45d7-b6b6-c61cec868057}
https://njpenterprises.sharepoint.com/sites/dev
At line:1 char:1
+ Apply-SPOProvisioningTemplate -Path "c:\temp\lookup-template.xml"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

[logfile2.txt](https://github.com/SharePoint/PnP/files/736063/logfile2.txt)

I have not tried on-premises yet.

Regards

Nigel

**Comment by VesaJuvonen** [comment] 2017-01-30 16:47
Hi Nigel, this indicates that the template has something off and without access on the template, we can't really reproduce the issue for detailed debugging. I'll also btw move this issue to PnP-Sites-Core repository, since this is clearly around the core component and engine.

**Comment by VesaJuvonen** [comment] 2017-01-30 16:48
This issue was moved to SharePoint/PnP-Sites-Core#1017

**Comment by VesaJuvonen** [comment] 2017-01-30 16:48
Issue relocated, so will close this one from here.

**Closed by VesaJuvonen** 2017-01-30 16:48 UTC
