### ISSUE TITLE
Overwrite page by provisioning template is not working

### ISSUE THREAD

**Issue by khha** [SharePoint/PnP#1575] opened 2016-12-23 12:50 UTC
####Which PnP repository should you use to report the issue?####
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I expected to overwrite the welcomepage by the template provisioning

#### Observed Behavior
The welcomepage content will be updated/appended to the existing welcome page.

#### Steps to Reproduce
Create template xml file. Add in this xml file a new file element default.aspx. Add a new file (default.aspx) in a subfolder (pages). Provision this template to a website. Go to the website and check if you see the new welcome page or a merge between the existing welcome page and the new page.

```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Templates ID="CONTAINER-PCDocument">
    <pnp:ProvisioningTemplate ID="TEMPLATE-PCDocument" Version="1" BaseSiteTemplate="BLANKINTERNET#0">
      <pnp:WebSettings NoCrawl="false" WelcomePage="Paginas/default.aspx" SiteLogo="" AlternateCSS="" MasterPageUrl="{masterpagecatalog}/BM.Intern.Werkruimte/Masterpage.Intern.Werkruimte.master" CustomMasterPageUrl="{masterpagecatalog}/BM.Intern.Werkruimte/Masterpage.Intern.Werkruimte.master" />
      <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="Gregorian" Collation="25" FirstDayOfWeek="Monday" FirstWeekOfYear="0" LocaleId="1043" ShowWeeks="false" Time24="true" TimeZone="3" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />
      <pnp:SupportedUILanguages>
        <pnp:SupportedUILanguage LCID="1043" />
      </pnp:SupportedUILanguages>
      <pnp:Files>
        <pnp:File Src="Pages\default.aspx" Folder="{site}/Paginas" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:Welkomstpagina}" />
            <pnp:Property Key="Title" Value="Custom welcome page" />
            <pnp:Property Key="PublishingPageLayout" Value="{masterpagecatalog}/BlankWebPartPage.aspx, Lege pagina met webonderdelen" />
            <pnp:Property Key="PublishingIsFurlPage" Value="False" />
            <pnp:Property Key="RobotsNoIndex" Value="False" />
            <pnp:Property Key="PublishingPageContent" Value="Welcome on this site" />
          </pnp:Properties>
        </pnp:File>
      </pnp:Files>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

As you see above I have implemented the property Overwrite:

`<pnp:File Src="Pages\default.aspx" Folder="{site}/Paginas" Overwrite="true" Level="Published">`

default.aspx:

```
<%@ Page Inherits="Microsoft.SharePoint.Publishing.TemplateRedirectionPage,Microsoft.SharePoint.Publishing,Version=15.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %> 
<%@ Reference VirtualPath="~TemplatePageUrl" %> 
<%@ Reference VirtualPath="~masterurl/custom.master" %>
<%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882">
    <head>
        <title>This is my custom welcome page</title>
   </head>
</html>
```

**Comment by VesaJuvonen** [comment] 2017-01-30 18:45
This issue was moved to SharePoint/PnP-Sites-Core#1019

**Comment by VesaJuvonen** [comment] 2017-01-30 18:46
Issue moved to right repository, since root cause or question relates on the PnP provisioning from Core component. Closing this one.

**Closed by VesaJuvonen** 2017-01-30 18:46 UTC
