### ISSUE TITLE
Provisioning.Modern.Console.REST project sites don't show in O365 Admin Center's "Manage Site Collections" 

### ISSUE THREAD

**Issue by RGrizzzz** [SharePoint/PnP#1676] opened 2017-06-13 14:29 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

- PnP Samples - https://github.com/OfficeDev/PnP
https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.Modern.Console.RESTAPI 

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit.

When I create a new site collection with this sample, the modern site creates successfully. In my O365 tenant's admin center, I browse to Manage Site Collections, and the site is not visible there. 

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.

Expecting to see the new site listed there. 

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Create a site with the tool. Look in admin center. 

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community.
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment] 2017-06-26 10:57
Hi RGrizzzz,
this is currently by design in the context of classic SPO admin experience. Same applies if you create modern group site by creating a group in Outlook or from any other endpoint, so it's not related to the REST API or the sample. In SP Summit videos (May) modern SharePoint Admin UI was announced and that will also show modern group sites in the SP admin views. Since this is by design and not related on the sample, will close the issue.

**Closed by VesaJuvonen** 2017-06-26 10:57 UTC
